sudo: required
services:
  - docker

before_install:
  - docker build -t angelgoez/simple-react-app -f Dockerfile.dev .

script:
  - docker run angelgoez/simple-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "simple-react-app"
  env: "SimpleReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-431017907402"
  bucket_path: "simple-react-app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"